server:
  port: 8000

zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    multiplications:
      path: /multiplications/**
      serviceId: multiplication
      strip-prefix: false
    results:
      path: /results/**
      serviceId: multiplication
      strip-prefix: false
    leaders:
      path: /leaders/**
      serviceId: gamification
      strip-prefix: false
    stats:
      path: /stats/**
      serviceId: gamification
      strip-prefix: false
    scores:
      path: /scores/**
      serviceId: gamification
      strip-prefix: false
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/